// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblAllStockValue
    {
        public int ProductID { get; set; }
        [Required]
        [StringLength(100)]
        public string ProductName { get; set; }
        public double ALAJOStockLevel { get; set; }
        public double KASOAStockLevel { get; set; }
        public double MADINAStockLevel { get; set; }
        public double PIGFARMStockLevel { get; set; }
        [StringLength(100)]
        public string ALAJOTotalStockLevel { get; set; }
        [StringLength(100)]
        public string KASOATotalStockLevel { get; set; }
        [StringLength(100)]
        public string MADINATotalStockLevel { get; set; }
        [StringLength(100)]
        public string PIGFARMTotalStockLevel { get; set; }
        [Column(TypeName = "money")]
        public decimal ALAJOTotalSellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal KASOATotalSellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal MadinaTotalSellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal PIGFARMTotalSellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal ALAJOTotalCostPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal KasoaTotalCostPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal MadinaTotalCostPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal PIGFARMTotalCostPrice { get; set; }
    }
}