// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblAllStockValueTemp
    {
        public int ProductID { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductName { get; set; }
        public double StockLevel { get; set; }
        [StringLength(100)]
        public string TotalStockLevel { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalSellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalCostPrice { get; set; }
        public int LocationID { get; set; }
        [Required]
        [StringLength(50)]
        public string LocationName { get; set; }
    }
}