// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblAccount
    {
        [Key]
        public int AccountID { get; set; }
        [StringLength(50)]
        public string AccountCode { get; set; }
        [Required]
        [StringLength(50)]
        public string AccountName { get; set; }
        public int AccountGroupID { get; set; }
    }
}