// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblBankBranch
    {
        [Key]
        public int BankBranchID { get; set; }
        [Required]
        [StringLength(50)]
        public string BankBranchName { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string POBox { get; set; }
        public string Address { get; set; }
        [StringLength(50)]
        public string EMailAddress { get; set; }
        [StringLength(50)]
        public string WebSite { get; set; }
        public int BankID { get; set; }
    }
}