// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblBankTransfer
    {
        [Key]
        public int BankTransferID { get; set; }
        public int FromAccountID { get; set; }
        public int ToAccountID { get; set; }
    }
}