// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblCurrencyRate
    {
        [Key]
        public int CurrencyRateID { get; set; }
        public double CurrencyBuyingRate { get; set; }
        public double CurrencySellingRate { get; set; }
        public int CurrencyID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDateTime { get; set; }
    }
}