// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblCustomer
    {
        [Key]
        public int CustomerID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime RegistrationDate { get; set; }
        [StringLength(32)]
        public string CustomerNo { get; set; }
        [Required]
        [StringLength(50)]
        public string CustomerName { get; set; }
        [StringLength(50)]
        public string PhoneNo { get; set; }
        [StringLength(50)]
        public string FaxNo { get; set; }
        [StringLength(50)]
        public string EMailAddress { get; set; }
        [StringLength(50)]
        public string WebSite { get; set; }
        public string Address { get; set; }
        [Column(TypeName = "money")]
        public decimal Debit { get; set; }
        [Column(TypeName = "money")]
        public decimal Credit { get; set; }
        [Column(TypeName = "money")]
        public decimal CreditLimit { get; set; }
        [Required]
        public bool? ApplyProtocolSetup { get; set; }
        public bool? IsActive { get; set; }
        public int ProtocolTypeID { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        public int CustomerTypeID { get; set; }
        public string Note { get; set; }
    }
}