// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblCountry
    {
        [Key]
        public int CountryID { get; set; }
        [Required]
        [StringLength(200)]
        public string CountryName { get; set; }
        [StringLength(200)]
        public string Nationality { get; set; }
        [StringLength(50)]
        public string CountryCode { get; set; }
    }
}