// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblCurrency
    {
        [Key]
        public int CurrencyID { get; set; }
        [Required]
        [StringLength(50)]
        public string CurrencyName { get; set; }
        [StringLength(3)]
        public string CurrencyCode { get; set; }
        [Required]
        [StringLength(50)]
        public string CurrencySymbol { get; set; }
        public double CurrencyBuyingRate { get; set; }
        public double CurrencySellingRate { get; set; }
    }
}