// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblCustomerType
    {
        [Key]
        public int CustomerTypeID { get; set; }
        [Required]
        [StringLength(50)]
        public string CustomerTypeName { get; set; }
        public double Discount { get; set; }
        public string Description { get; set; }
    }
}