// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblDailyStockLevel
    {
        [Key]
        public int DailyStockLevelID { get; set; }
        public int ProductID { get; set; }
        [Required]
        [StringLength(200)]
        public string StockLevel { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPrice { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StockLevelDate { get; set; }
        public int CompanyLocationID { get; set; }
        public int ProductCategoryID { get; set; }
    }
}