// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblExpense
    {
        [Key]
        public int ExpenseID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ExpenseDate { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int ExpenseTypeID { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDateTime { get; set; }
        public int ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public int CompanyLocationID { get; set; }
    }
}