// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblExpenditureTypeGroup
    {
        [Key]
        public int ExpenditureTypeGroupID { get; set; }
        [Required]
        [StringLength(10)]
        public string ExpenditureTypeGroupCode { get; set; }
        [Required]
        [StringLength(50)]
        public string ExpenditureTypeGroupName { get; set; }
    }
}