// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblEndOfShift
    {
        [StringLength(50)]
        public string Description { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        public int ShiftID { get; set; }
    }
}