// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblExpenditureType
    {
        [Key]
        public int ExpenditureTypeID { get; set; }
        [StringLength(10)]
        public string ExpenditureTypeCode { get; set; }
        [Required]
        [StringLength(50)]
        public string ExpenditureTypeName { get; set; }
        public string Description { get; set; }
        public int ExpenditureTypeGroupID { get; set; }
    }
}