// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblMonthlySaleReportByQty
    {
        public int ProductID { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(100)]
        public string January { get; set; }
        [StringLength(100)]
        public string February { get; set; }
        [StringLength(100)]
        public string March { get; set; }
        [StringLength(100)]
        public string April { get; set; }
        [StringLength(100)]
        public string May { get; set; }
        [StringLength(100)]
        public string June { get; set; }
        [StringLength(100)]
        public string July { get; set; }
        [StringLength(100)]
        public string August { get; set; }
        [StringLength(100)]
        public string September { get; set; }
        [StringLength(100)]
        public string October { get; set; }
        [StringLength(100)]
        public string November { get; set; }
        [StringLength(100)]
        public string December { get; set; }
    }
}