// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblMailDetail
    {
        [Key]
        public int MailDetailID { get; set; }
        public string MailRecipient { get; set; }
        [StringLength(200)]
        public string SenderEMailAddress { get; set; }
        [StringLength(200)]
        public string SenderPassword { get; set; }
        [StringLength(50)]
        public string Port { get; set; }
        [StringLength(50)]
        public string Host { get; set; }
    }
}