// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblOA
    {
        public tblOA()
        {
            tblOAFK = new HashSet<tblOAFK>();
        }

        [Key]
        public int OrderActivityID { get; set; }
        public int OrderID { get; set; }
        public int DeletedProductID { get; set; }
        public int SellingUnitID { get; set; }
        public double Qty { get; set; }
        [Column(TypeName = "money")]
        public decimal UnitPrice { get; set; }
        public double? TotalAmount { get; set; }
        public int WaiterID { get; set; }
        public int CashierID { get; set; }
        public int AdminID { get; set; }
        public int ShiftID { get; set; }
        public int ReasonID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime RemovedTime { get; set; }

        [InverseProperty("OrderActivity")]
        public virtual ICollection<tblOAFK> tblOAFK { get; set; }
    }
}