// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblOrderDetail
    {
        [Key]
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public int SellingUnitID { get; set; }
        public double Qty { get; set; }
        public double TotalQty { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal VAT { get; set; }
        [Column(TypeName = "money")]
        public decimal NHIL { get; set; }
        [Column(TypeName = "money")]
        public decimal TL { get; set; }
        public double? OrderDetailTotal { get; set; }
        public double? OrderDetailTotalCost { get; set; }
        public double? SellingPriceWithoutTax { get; set; }
        public double? OrderDetailTotalWithoutTax { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDatetime { get; set; }
        public int CreatedBy { get; set; }
        [StringLength(500)]
        public string ProductOption { get; set; }
        [StringLength(10)]
        public string ProductOptionID { get; set; }
        public int ProductCategoryLocationID { get; set; }
        public bool? NewlyInserted { get; set; }
    }
}