// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblOrder
    {
        [Key]
        public int OrderID { get; set; }
        [StringLength(32)]
        public string OrderNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime OrderDate { get; set; }
        [Column(TypeName = "money")]
        public decimal OrderTotal { get; set; }
        [Column(TypeName = "money")]
        public decimal Discount { get; set; }
        [Column(TypeName = "money")]
        public decimal NetTotal { get; set; }
        [Column(TypeName = "money")]
        public decimal TAX { get; set; }
        public int OrderTypeID { get; set; }
        public int WaiterID { get; set; }
        public int ChefID { get; set; }
        public int CustomerID { get; set; }
        [StringLength(50)]
        public string CustomerName { get; set; }
        public int UserID { get; set; }
        public int ShiftID { get; set; }
        public int DeletedBy { get; set; }
        public int TableID { get; set; }
        public int OrderStatusID { get; set; }
        public int DebitedBy { get; set; }
        public int ProtocolBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeletedTime { get; set; }
        public int CompanyLocationID { get; set; }
        [Column(TypeName = "money")]
        public decimal CashPayment { get; set; }
        [Column(TypeName = "money")]
        public decimal VisaPayment { get; set; }
        [Column(TypeName = "money")]
        public decimal WaiterPayment { get; set; }
        [Required]
        public bool? IsServiceCharge { get; set; }
        [Column(TypeName = "money")]
        public decimal ServiceCharge { get; set; }
        public int NoOfPeople { get; set; }
        public double DiscountPercentage { get; set; }
        [Column(TypeName = "money")]
        public decimal? OverAllTotal { get; set; }
        [Column(TypeName = "money")]
        public decimal MomoPayment { get; set; }
    }
}