// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblOrderDetailOption
    {
        [Key]
        public int OrderDetailOptionID { get; set; }
        public int OrderDetailID { get; set; }
        public int OptionID { get; set; }
    }
}