// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblProductTransfer
    {
        public int ProductID { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        public double QtyTransfered { get; set; }
        [StringLength(50)]
        public string TotalQtyTransfered { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalAmount { get; set; }
        public int CompanyLocationID { get; set; }
        [Required]
        [StringLength(50)]
        public string CompanyLocationName { get; set; }
    }
}