// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblProductOrderByStatus
    {
        public int ProductID { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        public double QtyOrdered { get; set; }
        [StringLength(50)]
        public string TotalQtyOrdered { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalAmount { get; set; }
        [StringLength(100)]
        public string CategoryName { get; set; }
        public int OrderTypeID { get; set; }
        [StringLength(50)]
        public string OrderTypeName { get; set; }
    }
}