// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblProductReportByShift
    {
        public int ProductID { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [Column(TypeName = "money")]
        public decimal? SellingPrice { get; set; }
        [StringLength(50)]
        public string CategoryGroupName { get; set; }
        public int PackageID { get; set; }
        public double? Pending { get; set; }
        public double? Cash { get; set; }
        public double? Credit { get; set; }
        public double? Protocol { get; set; }
        public double? Waiter { get; set; }
        public double? Deleted { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalAmount { get; set; }
        public double TotalQty { get; set; }
    }
}