// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblProduct
    {
        [Key]
        public int ProductID { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }
        [StringLength(100)]
        public string BarCode { get; set; }
        [Required]
        [StringLength(100)]
        public string ProductName { get; set; }
        [Required]
        [StringLength(151)]
        public string ProductCodeName { get; set; }
        public int BaseUnitID { get; set; }
        public int ProductCategoryID { get; set; }
        public int UserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "image")]
        public byte[] ProductPicture { get; set; }
        [Required]
        public bool? DoesItHaveStock { get; set; }
        [Required]
        public bool? AllowProtocol { get; set; }
        [Required]
        public bool? IsActive { get; set; }
    }
}