// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblPeriod
    {
        [Key]
        public int PeriodID { get; set; }
        [Required]
        [StringLength(50)]
        public string PeriodName { get; set; }
        public int NoOfDays { get; set; }
    }
}