// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblProductPortion
    {
        [Key]
        public int ProductPortionID { get; set; }
        public int ProductID { get; set; }
        public double NoOfPortion { get; set; }
    }
}