// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblProductStock
    {
        [Key]
        public int ProductStockID { get; set; }
        public int ProductID { get; set; }
        public double InitialStock { get; set; }
        public double StockLevel { get; set; }
        public double ReOrderLevel { get; set; }
        public int CompanyLocationID { get; set; }
    }
}