// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblProductRecipeSelector
    {
        public int ProductID { get; set; }
        public int PackageID { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        public double Qty { get; set; }
        public int ProductRecipeID { get; set; }
        public double? TotalCostPrice { get; set; }
    }
}