// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblProductPrice
    {
        [Key]
        public int ProductPriceID { get; set; }
        public int ProductID { get; set; }
        public int PackageID { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        public double QtyInPackage { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPriceWithoutTAX { get; set; }
        [Column(TypeName = "money")]
        public decimal VAT { get; set; }
        [Column(TypeName = "money")]
        public decimal NHIL { get; set; }
        [Column(TypeName = "money")]
        public decimal TL { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPriceWithTAX { get; set; }
        public bool ExemptVAT { get; set; }
        public bool ExemptNHIL { get; set; }
        public bool ExemptTL { get; set; }
        public int UserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Required]
        public bool? ShowInMenuList { get; set; }
        public int CompanyLocationID { get; set; }
    }
}