// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblProductCategory_Temp
    {
        public int ProductCategoryID { get; set; }
        [Required]
        [StringLength(100)]
        public string CategoryName { get; set; }
        public int CategoryGroupID { get; set; }
    }
}