// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblReason
    {
        [Key]
        public int ReasonID { get; set; }
        [StringLength(100)]
        public string ReasonDescription { get; set; }
    }
}