// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblShiftDetail
    {
        [Key]
        public int ShiftDetailID { get; set; }
        public int ShiftID { get; set; }
        public double GHC50 { get; set; }
        public double GHC50Amount { get; set; }
        public double GHC20 { get; set; }
        public double GHC20Amount { get; set; }
        public double GHC10 { get; set; }
        public double GHC10Amount { get; set; }
        public double GHC5 { get; set; }
        public double GHC5Amount { get; set; }
        public double GHC2 { get; set; }
        public double GHC2Amount { get; set; }
        public double GHC1 { get; set; }
        public double GHC1Coin { get; set; }
        [Column("50GP")]
        public double _50GP { get; set; }
        [Column("50GPAmount")]
        public double _50GPAmount { get; set; }
        [Column("20GP")]
        public double _20GP { get; set; }
        [Column("20GPAmount")]
        public double _20GPAmount { get; set; }
        [Column("10GP")]
        public double _10GP { get; set; }
        [Column("10GPAmount")]
        public double _10GPAmount { get; set; }
        [Column("5GP")]
        public double _5GP { get; set; }
        [Column("5GPAmount")]
        public double _5GPAmount { get; set; }
        [Column("1GP")]
        public double _1GP { get; set; }
        [Column("1GPAmount")]
        public double _1GPAmount { get; set; }
        public double DollarRate { get; set; }
        [Column(TypeName = "money")]
        public decimal DollarAmount { get; set; }
        public double? DollarTotal { get; set; }
        public double PoundRate { get; set; }
        [Column(TypeName = "money")]
        public decimal PoundAmount { get; set; }
        public double? PoundTotal { get; set; }
        public double EuroRate { get; set; }
        [Column(TypeName = "money")]
        public decimal EuroAmount { get; set; }
        public double? EuroTotal { get; set; }
        [Column(TypeName = "money")]
        public decimal OtherCurrencyAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal VISA { get; set; }
        [Column(TypeName = "money")]
        public decimal PettyCash { get; set; }
        [Column(TypeName = "money")]
        public decimal PromoVoucher { get; set; }
        [Column(TypeName = "money")]
        public decimal GateFee { get; set; }
        public string ItemToBuy { get; set; }
        public int UserID { get; set; }
        [Column(TypeName = "money")]
        public decimal? Momo { get; set; }
    }
}