// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblShiftReportByCategoryGroupTemp
    {
        public int ShiftID { get; set; }
        public int OrderStatusID { get; set; }
        public int ProductID { get; set; }
        public double Qty { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalAmount { get; set; }
        public int CategoryGroupID { get; set; }
    }
}