// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblStockPurchaseReturn
    {
        [Key]
        public int StockPurchaseID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StockPurchaseDate { get; set; }
        public int StockPurchaseDetailID { get; set; }
        public double QtyReturned { get; set; }
        public int UserID { get; set; }
    }
}