// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblStatus
    {
        [Key]
        public int StatusID { get; set; }
        [Required]
        [StringLength(50)]
        public string StatusName { get; set; }
    }
}