// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblStockPurchase
    {
        [Key]
        public int StockPurchaseID { get; set; }
        [StringLength(33)]
        public string StockPurchaseNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StockPurchaseDate { get; set; }
        public int SupplierID { get; set; }
        [Column(TypeName = "money")]
        public decimal StockPurchaseTotal { get; set; }
        [Column(TypeName = "money")]
        public decimal Discount { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetTotal { get; set; }
        public int UserID { get; set; }
        [StringLength(50)]
        public string InvoiceNo { get; set; }
        public int CompanyLocationID { get; set; }
    }
}