// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblShiftReport
    {
        [Key]
        public int ShiftReportID { get; set; }
        public int ShiftID { get; set; }
        [Column(TypeName = "money")]
        public decimal Pending { get; set; }
        [Column(TypeName = "money")]
        public decimal Cash { get; set; }
        [Column(TypeName = "money")]
        public decimal Credit { get; set; }
        [Column(TypeName = "money")]
        public decimal Protocol { get; set; }
        [Column(TypeName = "money")]
        public decimal WaiterTransfer { get; set; }
        [Column(TypeName = "money")]
        public decimal Deleted { get; set; }
    }
}