// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblShift
    {
        [Key]
        public int ShiftID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDateTime { get; set; }
        public int StartedBy { get; set; }
        public int EndedBy { get; set; }
        public int CompanyLocationID { get; set; }
        public bool IsClosed { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        [StringLength(69)]
        public string TimeRange { get; set; }
        public double ShiftDiscount { get; set; }
    }
}