// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblStockTransfer
    {
        [Key]
        public int StockTransferID { get; set; }
        [StringLength(33)]
        public string StockTransferNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StockTransferDate { get; set; }
        public int FromCompanyLocationID { get; set; }
        public int ToCompanyLocationID { get; set; }
        [Column(TypeName = "money")]
        public decimal StockTransferTotal { get; set; }
        public int StatusID { get; set; }
        public int UserID { get; set; }
    }
}