// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblStockDamage
    {
        [Key]
        public int StockDamageID { get; set; }
        [StringLength(33)]
        public string StockDamageNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StockDamageDate { get; set; }
        [Column(TypeName = "money")]
        public decimal StockDamageTotal { get; set; }
        public int UserID { get; set; }
        public int CompanyLocationID { get; set; }
    }
}