// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblStockLevel
    {
        public int ProductID { get; set; }
        public double StartingStockLevel { get; set; }
        public int ShiftID { get; set; }
        public int CompanyLocationID { get; set; }
        public double ClosingStockLevel { get; set; }
        public int BaseUnitID { get; set; }
        public double CorrectStock { get; set; }
        public string Remark { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        public double StockDifference { get; set; }
        public double StockVariance { get; set; }
    }
}