// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblUserFeature
    {
        [Key]
        public int UserFeatureID { get; set; }
        public int UserID { get; set; }
        public int FeatureID { get; set; }
    }
}