// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class tblWaiterSalaryHistory
    {
        [Key]
        public int WaiterSalaryHistoryID { get; set; }
        public int WaiterID { get; set; }
        [Column(TypeName = "money")]
        public decimal WaiterSalary { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDateTime { get; set; }
    }
}