// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwBankTransaction
    {
        public int TransactionID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime TransactionDate { get; set; }
        public int BankTransactionTypeID { get; set; }
        public string Notes { get; set; }
        public int BankID { get; set; }
        public int BankAccountID { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        [StringLength(50)]
        public string TransactedBy { get; set; }
        public bool IsPosted { get; set; }
        [StringLength(50)]
        public string ChequeNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChequeDate { get; set; }
        public int UserID { get; set; }
        [StringLength(50)]
        public string BankTransactionTypeName { get; set; }
        [StringLength(50)]
        public string AccountNo { get; set; }
        [Column(TypeName = "money")]
        public decimal? OpeningBalance { get; set; }
        [Column(TypeName = "money")]
        public decimal? CurrentBalance { get; set; }
        public int PaymentModeID { get; set; }
        [StringLength(50)]
        public string PaymentModeName { get; set; }
        [StringLength(50)]
        public string AccountName { get; set; }
        [StringLength(50)]
        public string BankName { get; set; }
        public int AccountID { get; set; }
        public int FromBankAccountID { get; set; }
        public int ToBankAccountID { get; set; }
        [StringLength(50)]
        public string ChequeBankName { get; set; }
        [StringLength(50)]
        public string FromBankAccountNo { get; set; }
        [StringLength(50)]
        public string ToBankAccountNo { get; set; }
    }
}