// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwCashWithdrawal
    {
        public int CashWithdrawalID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CashWithdrawalDate { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int UserID { get; set; }
        [StringLength(50)]
        public string CashWithdrawnBy { get; set; }
    }
}