// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwExpenseType
    {
        public int ExpenseTypeID { get; set; }
        [Required]
        [StringLength(50)]
        public string ExpenseTypeName { get; set; }
        public int ExpenseTypeGroupID { get; set; }
        [StringLength(10)]
        public string ExpenseTypeGroupCode { get; set; }
        [StringLength(50)]
        public string ExpenseTypeGroupName { get; set; }
    }
}