// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwExpenseDetail
    {
        public int ExpenseDetailID { get; set; }
        public int ExpenseID { get; set; }
        public int ProductID { get; set; }
        public int SellingUnitID { get; set; }
        public double Qty { get; set; }
        public double TotalQty { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        public double? ExpenseDetailTotal { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(50)]
        public string PackageName { get; set; }
    }
}