// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwExpense
    {
        public int ExpenseID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ExpenseDate { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDateTime { get; set; }
        public int ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public int ExpenseTypeID { get; set; }
        [Required]
        [StringLength(50)]
        public string ExpenseTypeName { get; set; }
        [StringLength(50)]
        public string CreatedByName { get; set; }
        [StringLength(50)]
        public string ModifiedByName { get; set; }
        public int CompanyLocationID { get; set; }
        [StringLength(50)]
        public string CompanyLocationName { get; set; }
        public int ExpenseTypeGroupID { get; set; }
        [StringLength(10)]
        public string ExpenseTypeGroupCode { get; set; }
        [StringLength(50)]
        public string ExpenseTypeGroupName { get; set; }
    }
}