// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwOrderDetail
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public int SellingUnitID { get; set; }
        public double Qty { get; set; }
        public double TotalQty { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal VAT { get; set; }
        [Column(TypeName = "money")]
        public decimal NHIL { get; set; }
        public double? OrderDetailTotal { get; set; }
        public double? OrderDetailTotalCost { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(151)]
        public string ProductCodeName { get; set; }
        [StringLength(50)]
        public string PackageName { get; set; }
        public bool? DoesItHaveStock { get; set; }
        [StringLength(50)]
        public string ProductCategoryLocationName { get; set; }
        public int? ProductCategoryID { get; set; }
        [StringLength(100)]
        public string CategoryName { get; set; }
        public double? SellingPriceWithoutTax { get; set; }
        public double? OrderDetailTotalWithoutTax { get; set; }
        [StringLength(100)]
        public string PrinterName { get; set; }
        [StringLength(500)]
        public string ProductOption { get; set; }
        [StringLength(606)]
        public string ProductNameWithOption { get; set; }
        [StringLength(10)]
        public string ProductOptionID { get; set; }
        [Column(TypeName = "money")]
        public decimal TL { get; set; }
        public int ProductCategoryLocationID { get; set; }
        [StringLength(50)]
        public string CategoryGroupName { get; set; }
        public int? CategoryGroupID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDatetime { get; set; }
        public bool? NewlyInserted { get; set; }
    }
}