// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwOrderActivity
    {
        public int OrderActivityID { get; set; }
        public int OrderID { get; set; }
        public int DeletedProductID { get; set; }
        public int SellingUnitID { get; set; }
        public double Qty { get; set; }
        [Column(TypeName = "money")]
        public decimal UnitPrice { get; set; }
        public double? TotalAmount { get; set; }
        public int CashierID { get; set; }
        public int AdminID { get; set; }
        public int ShiftID { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(50)]
        public string PackageName { get; set; }
        [StringLength(50)]
        public string Cashier { get; set; }
        [StringLength(50)]
        public string Admin { get; set; }
        [StringLength(69)]
        public string TimeRange { get; set; }
        [StringLength(100)]
        public string ReasonDescription { get; set; }
        [StringLength(32)]
        public string OrderNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime RemovedTime { get; set; }
        public int WaiterID { get; set; }
        [StringLength(50)]
        public string WaiterName { get; set; }
        public double QtyBefore { get; set; }
        public int ReasonID { get; set; }
        public int OrderDetailID { get; set; }
    }
}