// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwProductPrice
    {
        public int ProductPriceID { get; set; }
        public int ProductID { get; set; }
        public int PackageID { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        public double QtyInPackage { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPriceWithoutTAX { get; set; }
        [Column(TypeName = "money")]
        public decimal VAT { get; set; }
        [Column(TypeName = "money")]
        public decimal NHIL { get; set; }
        [Column(TypeName = "money")]
        public decimal TL { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPriceWithTAX { get; set; }
        public bool ExemptVAT { get; set; }
        public bool ExemptNHIL { get; set; }
        public bool ExemptTL { get; set; }
        public int UserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        public bool ShowInMenuList { get; set; }
        public int CompanyLocationID { get; set; }
        [StringLength(50)]
        public string PackageName { get; set; }
        [Required]
        [StringLength(100)]
        public string ProductName { get; set; }
        public bool DoesItHaveStock { get; set; }
        public bool AllowProtocol { get; set; }
        public bool IsActive { get; set; }
        public int ProductCategoryID { get; set; }
        [Required]
        [StringLength(50)]
        public string CompanyLocationName { get; set; }
        [Required]
        [StringLength(100)]
        public string CategoryName { get; set; }
    }
}