// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwProductStock
    {
        public int ProductStockID { get; set; }
        public int ProductID { get; set; }
        public double InitialStock { get; set; }
        public double StockLevel { get; set; }
        public double ReOrderLevel { get; set; }
        public int CompanyLocationID { get; set; }
        [StringLength(50)]
        public string CompanyLocationName { get; set; }
        [Required]
        [StringLength(100)]
        public string ProductName { get; set; }
        public int ProductCategoryID { get; set; }
        public int BaseUnitID { get; set; }
        [StringLength(100)]
        public string CategoryName { get; set; }
        [StringLength(50)]
        public string PackageName { get; set; }
        public bool DoesItHaveStock { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
    }
}