// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwShiftProductStockTaking
    {
        public int ProductID { get; set; }
        public int PackageID { get; set; }
        public double StockLevelBefore { get; set; }
        public double StockLevelAfter { get; set; }
        public double StockVariance { get; set; }
        public int UserID { get; set; }
        public int ShiftID { get; set; }
        public int CompanyLocationID { get; set; }
        [Required]
        [StringLength(100)]
        public string ProductName { get; set; }
        [Required]
        [StringLength(50)]
        public string PackageName { get; set; }
        public double QtyOut { get; set; }
        public double StockLevelAfterQtyOut { get; set; }
        public string Remark { get; set; }
    }
}