// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwStockPurchase
    {
        public int StockPurchaseID { get; set; }
        [StringLength(33)]
        public string StockPurchaseNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StockPurchaseDate { get; set; }
        public int SupplierID { get; set; }
        [Column(TypeName = "money")]
        public decimal StockPurchaseTotal { get; set; }
        [Column(TypeName = "money")]
        public decimal Discount { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetTotal { get; set; }
        public int UserID { get; set; }
        [StringLength(50)]
        public string InvoiceNo { get; set; }
        public int CompanyLocationID { get; set; }
        public int StockPurchaseDetailID { get; set; }
        public int ProductID { get; set; }
        public int SellingUnitID { get; set; }
        public double Qty { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        public double? StockPurchaseDetailTotal { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(50)]
        public string PackageName { get; set; }
        public double TotalQty { get; set; }
        [Required]
        [StringLength(50)]
        public string SupplierName { get; set; }
        [StringLength(32)]
        public string SupplierNo { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [Required]
        [StringLength(50)]
        public string CompanyLocationName { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
    }
}