// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwStockVariance
    {
        public int StockVarianceID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StockVarianceDate { get; set; }
        public int ProductID { get; set; }
        public int SellingUnitID { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPrice { get; set; }
        public double StockLevelBefore { get; set; }
        public double CurrentStockLevel { get; set; }
        public double StockDifference { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        public int UserID { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }
        [StringLength(100)]
        public string BarCode { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(151)]
        public string ProductCodeName { get; set; }
        [StringLength(50)]
        public string PackageName { get; set; }
        [StringLength(50)]
        public string TotalStockLevelBefore { get; set; }
        [StringLength(50)]
        public string TotalCurrentStockLevel { get; set; }
        [StringLength(50)]
        public string TotalStockDifference { get; set; }
        [Column(TypeName = "money")]
        public decimal StockDifferenceAmount { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
        public bool? DoesItHaveStock { get; set; }
    }
}