// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwStockLevel
    {
        public int ProductID { get; set; }
        public int ShiftID { get; set; }
        public int CompanyLocationID { get; set; }
        public double StartingStockLevel { get; set; }
        public double ClosingStockLevel { get; set; }
        public double StockDifference { get; set; }
        public int BaseUnitID { get; set; }
        [Required]
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(69)]
        public string TimeRange { get; set; }
        [Required]
        [StringLength(50)]
        public string PackageName { get; set; }
        [Required]
        [StringLength(100)]
        public string CategoryName { get; set; }
        public double CorrectStock { get; set; }
        public string Remark { get; set; }
        public double StockVariance { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal CostPrice { get; set; }
        [Required]
        [StringLength(50)]
        public string CompanyLocationName { get; set; }
        public bool IsClosed { get; set; }
    }
}