// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwStockDamage
    {
        public int StockDamageID { get; set; }
        [StringLength(33)]
        public string StockDamageNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StockDamageDate { get; set; }
        [Column(TypeName = "money")]
        public decimal StockDamageTotal { get; set; }
        public int UserID { get; set; }
        public int CompanyLocationID { get; set; }
        public int StockDamageDetailID { get; set; }
        public int ProductID { get; set; }
        public int SellingUnitID { get; set; }
        public double Qty { get; set; }
        [Column(TypeName = "money")]
        public decimal SellingPrice { get; set; }
        public double? StockDamageDetailTotal { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(151)]
        public string ProductCodeName { get; set; }
        [StringLength(50)]
        public string PackageName { get; set; }
        public double TotalQty { get; set; }
        public bool? DoesItHaveStock { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
        [Required]
        [StringLength(50)]
        public string CompanyLocationName { get; set; }
    }
}