// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwSupplierProduct
    {
        public int SupplierProductID { get; set; }
        public int ProductID { get; set; }
        public int SupplierID { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(100)]
        public string BarCode { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }
    }
}