// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwSupplierContactPerson
    {
        public int SupplierContactPersonID { get; set; }
        public int TitleID { get; set; }
        public int PositionID { get; set; }
        [Required]
        [StringLength(100)]
        public string ContactPersonName { get; set; }
        [Required]
        [StringLength(100)]
        public string MobilePhoneNo { get; set; }
        [StringLength(100)]
        public string HomePhoneNo { get; set; }
        [StringLength(100)]
        public string OfficePhoneNo { get; set; }
        public string Address { get; set; }
        public int SupplierID { get; set; }
        [StringLength(50)]
        public string TitleName { get; set; }
        [StringLength(50)]
        public string PositionName { get; set; }
    }
}