// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheLuxe.Entity
{
    public partial class vwUserActivity
    {
        public int UserActivityID { get; set; }
        public string Activity { get; set; }
        public int UserID { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ActivityDate { get; set; }
    }
}