// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace TheLuxe.Db
{
    public partial class Theluxeclub_CLIENTContext : DbContext
    {
        public virtual DbSet<tblOAFK> tblOAFK { get; set; }

        public Theluxeclub_CLIENTContext(DbContextOptions<Theluxeclub_CLIENTContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}